"""Добавлена таблица SettlementHistory

Revision ID: 954e448e1c7f
Revises: 393651cee23b
Create Date: 2025-03-25 14:06:48.797849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '954e448e1c7f'
down_revision = '393651cee23b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settlement_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('room_number', sa.Integer(), nullable=False),
    sa.Column('room_type', sa.String(length=50), nullable=True),
    sa.Column('payment_status', sa.String(length=50), nullable=True),
    sa.Column('check_in_date', sa.Date(), nullable=True),
    sa.Column('check_out_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('action_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settlement_history')
    # ### end Alembic commands ###
