"""Add user model

Revision ID: 98930cb6f836
Revises: 954e448e1c7f
Create Date: 2025-03-29 15:34:14.158489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98930cb6f836'
down_revision = '954e448e1c7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
